// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buawpglfbpamdniqfxar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1YXdwZ2xmYnBhbWRuaXFmeGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjc4NzEsImV4cCI6MjA2NDk0Mzg3MX0.FXXXW0N7yw00g30c5bGyQrArHG9PsIrEhut2f0jVKjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);